language: php
php:
  - 7.1.1  #versions we want to test
services:
  - mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
dist: trusty
sudo: required
before_install:
  - composer self-update --rollback
  - mysql -e 'CREATE DATABASE moodle;'
  - mysql -u root --password='' moodle < dump_sprint2.sql
  - mysql -e 'USE moodle; SHOW TABLES; DESCRIBE mdl_feedback;'
install:
  - composer require satooshi/php-coveralls:~0.6@stable #downloads coveralls
  - composer require --dev phpunit/dbunit
  - composer install
before_script:
  - mkdir -p ./tests/logs #make directory for coveralls log
script:
  - phpunit --version
  - composer dump-autoload #dump dependencies for travis ci
  - phpunit --coverage-clover ./tests/logs/clover.xml #generates a coverage report for coveralls
after_script:
  - php vendor/bin/coveralls -v #opens coveralls after build
